version: '3.8'

services:
  web:
    build:
      context: ../backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../backend:/app
      - app_settings_data:/app/settings
      - logs_data:/app/logs
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=calibrify.settings.development
      - DATABASE_URL=postgres://postgres:postgres@db:5432/calibrify
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=calibrify
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  nginx:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/static:/usr/share/nginx/html/static
      - ../frontend/templates:/usr/share/nginx/html/templates
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
  app_settings_data:
  logs_data: 